version: '3.8'
services:
  geonexus-db:
    image: postgis/postgis:16-3.4
    container_name: geonexus_postgis
    environment:
      POSTGRES_DB: geonexus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha_segura
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: